name: Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: dev # Upewnij się, że w GitHub Settings -> Environments masz stworzone środowisko o nazwie "env"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          # Użycie cudzysłowu zapobiega problemom z nowymi liniami w kluczu prywatnym
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh "$SSH_USER@$SSH_HOST" << 'EOF'
            set -e
            cd /root/projects/teamflow
      
            export PATH="$HOME/.bun/bin:$PATH"
            if ! command -v bun &> /dev/null; then
              echo "Bun is not installed. Installing Bun..."
              curl -fsSL https://bun.sh/install | bash
            fi
      
            # === Deploy ===
            git pull origin main
            bun install
            bun run build

            bunx prisma migrate deploy

            pm2 reload 10
            echo "Deploy zakończony pomyślnie."
          EOF
